BIST_SECTORS = {
    "BANK": "Bankacılık",
    "HOLD": "Holding",
    "GIDA": "Gıda",
    "INYH": "İnşaat",
    "MANA": "Maden",
    "OTVS": "Otomotiv",
    "PERK": "Perakende",
    "PETM": "Petrol Kimya",
    "REIT": "GYO",
    "SANI": "Sanayi",
    "SOGU": "Soğuk Demir Çelik",
    "TEKT": "Tekstil",
    "ULAS": "Ulaştırma",
    "ULKC": "Ülke Kalkınma",
    "YAPI": "Yapı",
    "YATR": "Yatırım",
    "YEDE": "Yedek Parça",
}

SIGNAL_MAP = {
    "Hemen SAT": {"color": "red", "emoji": "\U0001f534", "min_ratio": 3.0},
    "SAT": {"color": "orange", "emoji": "\U0001f7e0", "min_ratio": 1.5},
    "Kafana Gore": {"color": "yellow", "emoji": "\U0001f7e1", "min_ratio": 0.99},
    "AL": {"color": "green", "emoji": "\U0001f7e2", "min_ratio": 0.70},
    "Evi Barki Sat": {"color": "blue", "emoji": "\U0001f535", "min_ratio": 0.000001},
    "Borclu": {"color": "gray", "emoji": "\u26ab", "min_ratio": -float("inf")},
}

BIST_100 = [
    "ACSEL", "ADEL", "ADESE", "AEFES", "AFYON", "AGESA", "AGHOL", "AHGAZ",
    "AKBNK", "AKCNS", "AKENR", "AKFGY", "AKFYE", "AKGRT", "AKMGY", "AKSA",
    "AKSEN", "AKSGY", "AKSUE", "AKYHO", "ALARK", "ALBRK", "ALCAR", "ALFAS",
    "ALKIM", "ALKLC", "ALMAG", "ASELS", "ASGYO", "ASTOR", "ATAGY", "ATAKP",
    "ATATP", "AVGYO", "AVHOL", "AVTUR", "AYCES", "AYDEM", "AYEN", "AYES",
    "AYGAZ", "AYLN", "AYSMN", "AYTCE", "AYYAZ", "AZTEK", "BAGFS", "BAKAB",
    "BALAT", "BANVT", "BARMA", "BASCM", "BASGZ", "BAYRK", "BERA", "BEYAZ",
    "BFREN", "BIENY", "BIGCH", "BINBN", "BINHO", "BIOEN", "BIZIM", "BJKRD",
    "BLCYT", "BMSCH", "BMSTL", "BNTAS", "BOBET", "BORLS", "BORSA", "BORSN",
    "BRISA", "BRKO", "BRKSN", "BRKVY", "BRMEN", "BRLSM", "BRMEN", "BRSAN",
    "BRKO", "BRKVY", "BRYAT", "BSOKE", "BTCIM", "BUCIM", "BURCE", "BURVA",
    "CANTE", "CASA", "CATES", "CCOLA", "CELHA", "CEMAS", "CEMTS", "CEOEM",
    "CGCAM", "CLEBI", "CMBTN", "CMNET", "COLGD", "COMDO", "CONSE", "COSMO",
    "CRDFA", "CRFSA", "CUSAN", "CVKMD", "CWENE", "DAGHL", "DAGI", "DAPGM",
    "DCTTR", "DENGE", "DERHL", "DERIM", "DESA", "DESPN", "DEVCN", "DGATE",
    "DGNMO", "DITAS", "DMRGD", "DMSAS", "DNISI", "DOAS", "DOBUR", "DOFER",
    "DOGUB", "DOHOL", "DOKTA", "DURDO", "DYOBY", "DZGYO", "ECILC", "ECZYT",
    "EDATA", "EDIP", "EGEEN", "EGEPO", "EGGUB", "EGPRO", "EGSER", "EKGYO",
    "EKIZ", "EKOS", "EKIZC", "EKRAR", "EKGYO", "ELITE", "EMKEL", "EMNIS",
    "EMNMA", "ENJSA", "ENKAI", "ENKAI", "ENSRI", "ENTRA", "EPLAS", "ERBOS",
    "ERCB", "EREGL", "ERSU", "ESCAR", "ESCOM", "ESEMS", "ETILR", "ETYAT",
    "EUHOL", "EUPWR", "EUREN", "EUTHR", "FADE", "FLAP", "FMIZP", "FONET",
    "FORMT", "FORTE", "FRIGO", "FROTS", "FZLGY", "GARAN", "GARFA", "GEDIK",
    "GEDZA", "GENIL", "GENTS", "GEREL", "GESAN", "GIPTA", "GLBMD", "GLCVY",
    "GLYHO", "GMTAS", "GOKNR", "GOLTS", "GOODY", "GOZDE", "GRSEL", "GRTRK",
    "GRVGD", "GSDDE", "GSDHO", "GSRAY", "GUBRF", "GZNMI", "HALKB", "HATEK",
    "HDFGS", "HEDEF", "HEKTS", "HELVA", "HKTM", "HLGYO", "HTTBT", "HUBVC",
    "HUNER", "HURGZ", "ICBCT", "ICUGS", "IDGYO", "IEYHO", "IHAAS", "IHEVA",
    "IHGZT", "IHLAS", "IHLGM", "IHYAY", "IMASM", "INDES", "INFO", "INTEM",
    "INVEO", "INVES", "IPEKE", "ISCTR", "ISDMR", "ISFIN", "ISGSY", "ISGYO",
    "ISHOL", "ISKPL", "ISKUR", "ISMEN", "ISSEN", "ISYAT", "IZFAS", "IZINV",
    "IZMDC", "IZENR", "IZTAB", "IZYDO", "IZYMO", "KAPLM", "KAREL", "KARSN",
    "KARTN", "KARYE", "KATMR", "KBORU", "KCAER", "KCHOL", "KCONR", "KCRN",
    "KFEIN", "KFEIN", "KFXPTR", "KIMMR", "KLGYO", "KLKIM", "KLMSN", "KLNMA",
    "KLRHO", "KLSER", "KLSYN", "KLSER", "KLUYN", "KMPUR", "KNFRT", "KONKA",
    "KONTR", "KONYA", "KOPOL", "KORDS", "KRGYO", "KRONT", "KRPLN", "KRSTL",
    "KRTEK", "KRVMD", "KSTUR", "KTLEV", "KTSKR", "KUVVA", "KUYAS", "KZBGY",
    "KZGYO", "LIDER", "LIDFA", "LILAK", "LINK", "LKMNH", "LOGO", "LUKSK",
    "MAALT", "MACKO", "MAGEN", "MAKIM", "MAKTK", "MARKA", "MARBL", "MAXFM",
    "MEDTR", "MEGAP", "MEKAG", "MERCN", "MERIT", "MERKO", "MERVK", "MERYS",
    "METRO", "METUR", "MGFLT", "MGROS", "MHRGY", "MIPAZ", "MMCAS", "MNDRS",
    "MNDTR", "MOBTL", "MOGAN", "MOPAS", "MPARK", "MRTGG", "MRSHL", "MSGYO",
    "MTRYO", "MTNVH", "MTRKS", "MTRY", "MZHLD", "NATEN", "NETAS", "NIBAS",
    "NTGAZ", "NTGYO", "NTHOL", "NUGYO", "NUHCM", "OBAMS", "OBASE", "ODAS",
    "ODSN", "ONCSM", "ONDOF", "ONRWY", "ORBMA", "ORCAY", "ORGE", "ORMA",
    "OSMEN", "OSTIM", "OTKAR", "OTTO", "OYAKC", "OYAYO", "OYEN", "OYYAT",
    "OZGYO", "OZKGY", "OZRDN", "OZSUB", "OZTGY", "OZYSR", "PAGYO", "PAMEL",
    "PAPIL", "PARSN", "PASEU", "PCILT", "PEKGY", "PENGD", "PENTA", "PETKM",
    "PETUN", "PGSUS", "PINFO", "PINMA", "PKART", "PKENT", "PLTUR", "PNLSN",
    "PNRGY", "POLHO", "POLTK", "PRDGY", "PRKAB", "PRKME", "PRZMY", "PSGYO",
    "PSGYO", "QNBFB", "QNBFL", "QUAGR", "QNBGF", "RAYSG", "REEDR", "RGYAS",
    "RNPOL", "RODRG", "RODRS", "ROYAL", "RUBNS", "RYSAS", "SAHOL", "SAMAT",
    "SANEL", "SANFM", "SANKN", "SASA", "SAYAS", "SDTTR", "SEGYO", "SEKFK",
    "SEKUR", "SELEC", "SELGD", "SELVA", "SEYKM", "SILVR", "SISE", "SKBNK",
    "SKYLP", "SKYMD", "SMART", "SNGYO", "SNICA", "SNKRN", "SNPAM", "SNPHR",
    "SOKM", "SONME", "SRVGY", "SUMAS", "SUNTK", "SUWEN", "TABGD", "TABUR",
    "TATGD", "TATVS", "TAVHL", "TBORG", "TCELL", "TDGYO", "TEKTU", "TERA",
    "TEZOL", "TETMT", "TEZYN", "TGSAS", "THYAO", "TKFEN", "TKNSA", "TLIGT",
    "TMPOL", "TMSN", "TNZTP", "TOASO", "TRCAS", "TRGYO", "TRILC", "TSGYO",
    "TSKB", "TSMGS", "TSPOR", "TSKB", "TTKOM", "TTRAK", "TUCLK", "TUKAS",
    "TUREX", "TURSG", "UFUK", "ULAS", "ULUFA", "ULUSE", "ULUUN", "UMPAS",
    "UNLU", "USAK", "USREF", "USYES", "UYUNM", "UZERB", "UZERB", "VAKBN",
    "VAKFN", "VAKFN", "VAKKO", "VAKUM", "VBTYZ", "VERUS", "VESTEL", "VKFYO",
    "VKGYO", "VKING", "VKFN", "VRTX", "YAEMN", "YEOTK", "YEPPG", "YGGYO",
    "YGYO", "YATAS", "YAYLA", "YBTAS", "YDGYO", "YEGGY", "YEPLT", "YEŞİ",
    "YGGYO", "YGYO", "YHYGY", "YKBNK", "YKSLN", "YONGA", "YUNSA", "YYAPI",
    "YYLGD", "YYLGN", "YYYO", "ZEDUR", "ZOREN", "ZRGYO", "ZRGYO",
]

BIST_30 = [
    "AKBNK", "AKSEN", "ASELS", "BIMAS", "BRSAN", "EKGYO", "ENKAI", "EREGL",
    "FROTO", "GARAN", "GUBRF", "HALKB", "ISCTR", "KCHOL", "KONTR", "KOZAL",
    "KRDMD", "PGSUS", "SAHOL", "SASA", "SISE", "TCELL", "THYAO", "TOASO",
    "TTKOM", "TUPRS", "TURSE", "VAKBN", "YKBNK", "YATAS",
]
